"""add unique guest id document

Revision ID: 1c16643145dc
Revises: b5714ebe8357
Create Date: 2026-10-08 00:37:39.149050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c16643145dc'
down_revision: Union[str, Sequence[str], None] = 'b5714ebe8357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_guest_id_document', 'guests', ['id_type', 'id_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_guest_id_document', 'guests', type_='unique')
    # ### end Alembic commands ###
